/**:
  ros__parameters:
    # plugin_denylist:
    #   # common
    #   - actuator_control
    #   - ftp
    #   - hil
    #   # extras
    #   - altitude
    #   - debug_value
    #   - image_pub
    #   - px4flow
    #   - vibration
    #   - vision_speed_estimate
    #   - wheel_odometry

    # plugin_allowlist:
    #   - 'sys_*'

    plugin_allowlist:
      # Check https://github.com/mavlink/mavros/blob/ros2/mavros/mavros_plugins.xml

      # Essential plugins
      - sys_status        # Handles connection status and heartbeats
      - sys_time          # For system time info
      - home_position     # Home information
      - command           # For sending commands/services (arming, mode changes)
      - param             # For getting/setting parameters
      
      # Required for state estimation and control
      - imu               # IMU data
      - global_position   # GPS data
      - local_position    # Odometry data
      - setpoint_position # For sending position commands
      - setpoint_velocity # For sending velocity commands
      - setpoint_accel    # For sending acceleration commands
      - waypoint          # For mission manipulation
      - rc_io             # For RC override
      - vfr_hud           # For airspeed and altitude info
